spring:
  application:
    name: kafkatest

  kafka:
    retry-topic-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      properties:
        enable.idempotence: true
        retry.backoff.ms: 1000
      topics:
        topic1: topic1
        topic2: topic2
        topic3: topic3
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: test-group-id
      properties.spring.json.trusted.packages: "*"
